
spec:
  template:
    spec:
      containers:
      - name: nginx
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["/bin/sh","-c"]
        args: ["mkdir -p /usr/share/nginx/json && \
                rm -f /etc/nginx/conf.d/custom.conf  && \
                mv  /etc/nginx/conf.d/default.not_conf /etc/nginx/conf.d/default.conf  2>/dev/null; true && \
                nginx -g 'daemon off;'"]
        volumeMounts:
        - name: configmap-102
          mountPath: /etc/kube-box
      volumes:
      - name: configmap-102
        configMap:
          name: configmap-102

