apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: kube-box
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
  dnsDomain: cluster.local
controllerManager:
  extraArgs:
    cluster-cidr: 10.244.0.0/16
apiServer:
  extraArgs:
    advertise-address: ${KUBE_ADVERTISE_ADDRESS}
  certSANs:
    - 127.0.0.1
    - localhost
    