apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: kube-box
networking:
  podSubnet: ${KUBE_CLUSTER_CIDR}
  serviceSubnet: ${KUBE_SERVICE_ADDRESSES}
  dnsDomain: ${KUBE_CLUSTER_DOMAIN}
controllerManager:
  extraArgs:
    cluster-cidr: ${KUBE_CLUSTER_CIDR}
apiServer:
  extraArgs:
    advertise-address: ${KUBE_ADVERTISE_ADDRESS}
  certSANs:
    - 127.0.0.1
    - localhost
